//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PA2Reference
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PhoneInfoResponse", Namespace="http://www.serviceobjects.com")]
    public partial class PhoneInfoResponse : object
    {
        
        private PA2Reference.PhoneInfo PhoneInfoField;
        
        private PA2Reference.PA2Error ErrorField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public PA2Reference.PhoneInfo PhoneInfo
        {
            get
            {
                return this.PhoneInfoField;
            }
            set
            {
                this.PhoneInfoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public PA2Reference.PA2Error Error
        {
            get
            {
                return this.ErrorField;
            }
            set
            {
                this.ErrorField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PhoneInfo", Namespace="http://www.serviceobjects.com")]
    public partial class PhoneInfo : object
    {
        
        private string PhoneField;
        
        private string NameField;
        
        private string AddressField;
        
        private string CityField;
        
        private string StateField;
        
        private string PostalCodeField;
        
        private string IsResidentialField;
        
        private string CertaintyField;
        
        private string LineTypeField;
        
        private string DebugField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone
        {
            get
            {
                return this.PhoneField;
            }
            set
            {
                this.PhoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Address
        {
            get
            {
                return this.AddressField;
            }
            set
            {
                this.AddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string City
        {
            get
            {
                return this.CityField;
            }
            set
            {
                this.CityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string State
        {
            get
            {
                return this.StateField;
            }
            set
            {
                this.StateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string PostalCode
        {
            get
            {
                return this.PostalCodeField;
            }
            set
            {
                this.PostalCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string IsResidential
        {
            get
            {
                return this.IsResidentialField;
            }
            set
            {
                this.IsResidentialField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string Certainty
        {
            get
            {
                return this.CertaintyField;
            }
            set
            {
                this.CertaintyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public string LineType
        {
            get
            {
                return this.LineTypeField;
            }
            set
            {
                this.LineTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string Debug
        {
            get
            {
                return this.DebugField;
            }
            set
            {
                this.DebugField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PA2Error", Namespace="http://www.serviceobjects.com")]
    public partial class PA2Error : object
    {
        
        private string TypeField;
        
        private string TypeCodeField;
        
        private string DescField;
        
        private string DescCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TypeCode
        {
            get
            {
                return this.TypeCodeField;
            }
            set
            {
                this.TypeCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Desc
        {
            get
            {
                return this.DescField;
            }
            set
            {
                this.DescField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string DescCode
        {
            get
            {
                return this.DescCodeField;
            }
            set
            {
                this.DescCodeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.serviceobjects.com", ConfigurationName="PA2Reference.IPhoneAppend2")]
    public interface IPhoneAppend2
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.serviceobjects.com/IPhoneAppend2/PhoneAppend_QUERYGETXML", ReplyAction="http://www.serviceobjects.com/IPhoneAppend2/PhoneAppend_QUERYGETXMLResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="PhoneInfoResponse")]
        System.Threading.Tasks.Task<PA2Reference.PhoneInfoResponse> PhoneAppend_QUERYGETXMLAsync(string FullName, string FirstName, string LastName, string Address, string City, string State, string PostalCode, string LicenseKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.serviceobjects.com/IPhoneAppend2/PhoneAppend_QUERYGETJSON", ReplyAction="http://www.serviceobjects.com/IPhoneAppend2/PhoneAppend_QUERYGETJSONResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="PhoneInfoResponse")]
        System.Threading.Tasks.Task<PA2Reference.PhoneInfoResponse> PhoneAppend_QUERYGETJSONAsync(string FullName, string FirstName, string LastName, string Address, string City, string State, string PostalCode, string LicenseKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.serviceobjects.com/IPhoneAppend2/PhoneAppend_GETXML", ReplyAction="http://www.serviceobjects.com/IPhoneAppend2/PhoneAppend_GETXMLResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="PhoneInfoResponse")]
        System.Threading.Tasks.Task<PA2Reference.PhoneInfoResponse> PhoneAppend_GETXMLAsync(string FullName, string FirstName, string LastName, string Address, string City, string State, string PostalCode, string LicenseKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.serviceobjects.com/IPhoneAppend2/PhoneAppend_GETJSON", ReplyAction="http://www.serviceobjects.com/IPhoneAppend2/PhoneAppend_GETJSONResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="PhoneInfoResponse")]
        System.Threading.Tasks.Task<PA2Reference.PhoneInfoResponse> PhoneAppend_GETJSONAsync(string FullName, string FirstName, string LastName, string Address, string City, string State, string PostalCode, string LicenseKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.serviceobjects.com/IPhoneAppend2/PhoneAppend_POST", ReplyAction="http://www.serviceobjects.com/IPhoneAppend2/PhoneAppend_POSTResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="PhoneInfoResponse")]
        System.Threading.Tasks.Task<PA2Reference.PhoneInfoResponse> PhoneAppend_POSTAsync(string FullName, string FirstName, string LastName, string Address, string City, string State, string PostalCode, string LicenseKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.serviceobjects.com/IPhoneAppend2/PhoneAppend_PUT", ReplyAction="http://www.serviceobjects.com/IPhoneAppend2/PhoneAppend_PUTResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="PhoneInfoResponse")]
        System.Threading.Tasks.Task<PA2Reference.PhoneInfoResponse> PhoneAppend_PUTAsync(string FullName, string FirstName, string LastName, string Address, string City, string State, string PostalCode, string LicenseKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.serviceobjects.com/IPhoneAppend2/PhoneAppend_DELETE", ReplyAction="http://www.serviceobjects.com/IPhoneAppend2/PhoneAppend_DELETEResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="PhoneInfoResponse")]
        System.Threading.Tasks.Task<PA2Reference.PhoneInfoResponse> PhoneAppend_DELETEAsync(string FullName, string FirstName, string LastName, string Address, string City, string State, string PostalCode, string LicenseKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.serviceobjects.com/IPhoneAppend2/PhoneAppend", ReplyAction="http://www.serviceobjects.com/IPhoneAppend2/PhoneAppendResponse")]
        System.Threading.Tasks.Task<PA2Reference.PhoneInfoResponse> PhoneAppendAsync(string FullName, string FirstName, string LastName, string Address, string City, string State, string PostalCode, string LicenseKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.serviceobjects.com/IPhoneAppend2/BusinessPhoneAppend_QUERYGETXML", ReplyAction="http://www.serviceobjects.com/IPhoneAppend2/BusinessPhoneAppend_QUERYGETXMLRespon" +
            "se")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="PhoneInfoResponse")]
        System.Threading.Tasks.Task<PA2Reference.PhoneInfoResponse> BusinessPhoneAppend_QUERYGETXMLAsync(string BusinessName, string Address, string City, string State, string PostalCode, string LicenseKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.serviceobjects.com/IPhoneAppend2/BusinessPhoneAppend_QUERYGETJSON", ReplyAction="http://www.serviceobjects.com/IPhoneAppend2/BusinessPhoneAppend_QUERYGETJSONRespo" +
            "nse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="PhoneInfoResponse")]
        System.Threading.Tasks.Task<PA2Reference.PhoneInfoResponse> BusinessPhoneAppend_QUERYGETJSONAsync(string BusinessName, string Address, string City, string State, string PostalCode, string LicenseKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.serviceobjects.com/IPhoneAppend2/BusinessPhoneAppend_GETXML", ReplyAction="http://www.serviceobjects.com/IPhoneAppend2/BusinessPhoneAppend_GETXMLResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="PhoneInfoResponse")]
        System.Threading.Tasks.Task<PA2Reference.PhoneInfoResponse> BusinessPhoneAppend_GETXMLAsync(string BusinessName, string Address, string City, string State, string PostalCode, string LicenseKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.serviceobjects.com/IPhoneAppend2/BusinessPhoneAppend_GETJSON", ReplyAction="http://www.serviceobjects.com/IPhoneAppend2/BusinessPhoneAppend_GETJSONResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="PhoneInfoResponse")]
        System.Threading.Tasks.Task<PA2Reference.PhoneInfoResponse> BusinessPhoneAppend_GETJSONAsync(string BusinessName, string Address, string City, string State, string PostalCode, string LicenseKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.serviceobjects.com/IPhoneAppend2/BusinessPhoneAppend_POST", ReplyAction="http://www.serviceobjects.com/IPhoneAppend2/BusinessPhoneAppend_POSTResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="PhoneInfoResponse")]
        System.Threading.Tasks.Task<PA2Reference.PhoneInfoResponse> BusinessPhoneAppend_POSTAsync(string BusinessName, string Address, string City, string State, string PostalCode, string LicenseKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.serviceobjects.com/IPhoneAppend2/BusinessPhoneAppend_PUT", ReplyAction="http://www.serviceobjects.com/IPhoneAppend2/BusinessPhoneAppend_PUTResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="PhoneInfoResponse")]
        System.Threading.Tasks.Task<PA2Reference.PhoneInfoResponse> BusinessPhoneAppend_PUTAsync(string BusinessName, string Address, string City, string State, string PostalCode, string LicenseKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.serviceobjects.com/IPhoneAppend2/BusinessPhoneAppend_DELETE", ReplyAction="http://www.serviceobjects.com/IPhoneAppend2/BusinessPhoneAppend_DELETEResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="PhoneInfoResponse")]
        System.Threading.Tasks.Task<PA2Reference.PhoneInfoResponse> BusinessPhoneAppend_DELETEAsync(string BusinessName, string Address, string City, string State, string PostalCode, string LicenseKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.serviceobjects.com/IPhoneAppend2/BusinessPhoneAppend", ReplyAction="http://www.serviceobjects.com/IPhoneAppend2/BusinessPhoneAppendResponse")]
        System.Threading.Tasks.Task<PA2Reference.PhoneInfoResponse> BusinessPhoneAppendAsync(string BusinessName, string Address, string City, string State, string PostalCode, string LicenseKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.serviceobjects.com/IPhoneAppend2/CompositePhoneAppend_QUERYGETXML", ReplyAction="http://www.serviceobjects.com/IPhoneAppend2/CompositePhoneAppend_QUERYGETXMLRespo" +
            "nse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="PhoneInfoResponse")]
        System.Threading.Tasks.Task<PA2Reference.PhoneInfoResponse> CompositePhoneAppend_QUERYGETXMLAsync(string Name, string Address, string City, string State, string PostalCode, string isBusiness, string LicenseKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.serviceobjects.com/IPhoneAppend2/CompositePhoneAppend_QUERYGETJSON", ReplyAction="http://www.serviceobjects.com/IPhoneAppend2/CompositePhoneAppend_QUERYGETJSONResp" +
            "onse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="PhoneInfoResponse")]
        System.Threading.Tasks.Task<PA2Reference.PhoneInfoResponse> CompositePhoneAppend_QUERYGETJSONAsync(string Name, string Address, string City, string State, string PostalCode, string isBusiness, string LicenseKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.serviceobjects.com/IPhoneAppend2/CompositePhoneAppend_GETXML", ReplyAction="http://www.serviceobjects.com/IPhoneAppend2/CompositePhoneAppend_GETXMLResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="PhoneInfoResponse")]
        System.Threading.Tasks.Task<PA2Reference.PhoneInfoResponse> CompositePhoneAppend_GETXMLAsync(string Name, string Address, string City, string State, string PostalCode, string isBusiness, string LicenseKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.serviceobjects.com/IPhoneAppend2/CompositePhoneAppend_GETJSON", ReplyAction="http://www.serviceobjects.com/IPhoneAppend2/CompositePhoneAppend_GETJSONResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="PhoneInfoResponse")]
        System.Threading.Tasks.Task<PA2Reference.PhoneInfoResponse> CompositePhoneAppend_GETJSONAsync(string Name, string Address, string City, string State, string PostalCode, string isBusiness, string LicenseKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.serviceobjects.com/IPhoneAppend2/CompositePhoneAppend_POST", ReplyAction="http://www.serviceobjects.com/IPhoneAppend2/CompositePhoneAppend_POSTResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="PhoneInfoResponse")]
        System.Threading.Tasks.Task<PA2Reference.PhoneInfoResponse> CompositePhoneAppend_POSTAsync(string Name, string Address, string City, string State, string PostalCode, string isBusiness, string LicenseKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.serviceobjects.com/IPhoneAppend2/CompositePhoneAppend_PUT", ReplyAction="http://www.serviceobjects.com/IPhoneAppend2/CompositePhoneAppend_PUTResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="PhoneInfoResponse")]
        System.Threading.Tasks.Task<PA2Reference.PhoneInfoResponse> CompositePhoneAppend_PUTAsync(string Name, string Address, string City, string State, string PostalCode, string isBusiness, string LicenseKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.serviceobjects.com/IPhoneAppend2/CompositePhoneAppend_DELETE", ReplyAction="http://www.serviceobjects.com/IPhoneAppend2/CompositePhoneAppend_DELETEResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="PhoneInfoResponse")]
        System.Threading.Tasks.Task<PA2Reference.PhoneInfoResponse> CompositePhoneAppend_DELETEAsync(string Name, string Address, string City, string State, string PostalCode, string isBusiness, string LicenseKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.serviceobjects.com/IPhoneAppend2/CompositePhoneAppend", ReplyAction="http://www.serviceobjects.com/IPhoneAppend2/CompositePhoneAppendResponse")]
        System.Threading.Tasks.Task<PA2Reference.PhoneInfoResponse> CompositePhoneAppendAsync(string Name, string Address, string City, string State, string PostalCode, string isBusiness, string LicenseKey);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface IPhoneAppend2Channel : PA2Reference.IPhoneAppend2, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class PhoneAppend2Client : System.ServiceModel.ClientBase<PA2Reference.IPhoneAppend2>, PA2Reference.IPhoneAppend2
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public PhoneAppend2Client() : 
                base(PhoneAppend2Client.GetDefaultBinding(), PhoneAppend2Client.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.soap.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PhoneAppend2Client(EndpointConfiguration endpointConfiguration) : 
                base(PhoneAppend2Client.GetBindingForEndpoint(endpointConfiguration), PhoneAppend2Client.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PhoneAppend2Client(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(PhoneAppend2Client.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PhoneAppend2Client(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(PhoneAppend2Client.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PhoneAppend2Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<PA2Reference.PhoneInfoResponse> PhoneAppend_QUERYGETXMLAsync(string FullName, string FirstName, string LastName, string Address, string City, string State, string PostalCode, string LicenseKey)
        {
            return base.Channel.PhoneAppend_QUERYGETXMLAsync(FullName, FirstName, LastName, Address, City, State, PostalCode, LicenseKey);
        }
        
        public System.Threading.Tasks.Task<PA2Reference.PhoneInfoResponse> PhoneAppend_QUERYGETJSONAsync(string FullName, string FirstName, string LastName, string Address, string City, string State, string PostalCode, string LicenseKey)
        {
            return base.Channel.PhoneAppend_QUERYGETJSONAsync(FullName, FirstName, LastName, Address, City, State, PostalCode, LicenseKey);
        }
        
        public System.Threading.Tasks.Task<PA2Reference.PhoneInfoResponse> PhoneAppend_GETXMLAsync(string FullName, string FirstName, string LastName, string Address, string City, string State, string PostalCode, string LicenseKey)
        {
            return base.Channel.PhoneAppend_GETXMLAsync(FullName, FirstName, LastName, Address, City, State, PostalCode, LicenseKey);
        }
        
        public System.Threading.Tasks.Task<PA2Reference.PhoneInfoResponse> PhoneAppend_GETJSONAsync(string FullName, string FirstName, string LastName, string Address, string City, string State, string PostalCode, string LicenseKey)
        {
            return base.Channel.PhoneAppend_GETJSONAsync(FullName, FirstName, LastName, Address, City, State, PostalCode, LicenseKey);
        }
        
        public System.Threading.Tasks.Task<PA2Reference.PhoneInfoResponse> PhoneAppend_POSTAsync(string FullName, string FirstName, string LastName, string Address, string City, string State, string PostalCode, string LicenseKey)
        {
            return base.Channel.PhoneAppend_POSTAsync(FullName, FirstName, LastName, Address, City, State, PostalCode, LicenseKey);
        }
        
        public System.Threading.Tasks.Task<PA2Reference.PhoneInfoResponse> PhoneAppend_PUTAsync(string FullName, string FirstName, string LastName, string Address, string City, string State, string PostalCode, string LicenseKey)
        {
            return base.Channel.PhoneAppend_PUTAsync(FullName, FirstName, LastName, Address, City, State, PostalCode, LicenseKey);
        }
        
        public System.Threading.Tasks.Task<PA2Reference.PhoneInfoResponse> PhoneAppend_DELETEAsync(string FullName, string FirstName, string LastName, string Address, string City, string State, string PostalCode, string LicenseKey)
        {
            return base.Channel.PhoneAppend_DELETEAsync(FullName, FirstName, LastName, Address, City, State, PostalCode, LicenseKey);
        }
        
        public System.Threading.Tasks.Task<PA2Reference.PhoneInfoResponse> PhoneAppendAsync(string FullName, string FirstName, string LastName, string Address, string City, string State, string PostalCode, string LicenseKey)
        {
            return base.Channel.PhoneAppendAsync(FullName, FirstName, LastName, Address, City, State, PostalCode, LicenseKey);
        }
        
        public System.Threading.Tasks.Task<PA2Reference.PhoneInfoResponse> BusinessPhoneAppend_QUERYGETXMLAsync(string BusinessName, string Address, string City, string State, string PostalCode, string LicenseKey)
        {
            return base.Channel.BusinessPhoneAppend_QUERYGETXMLAsync(BusinessName, Address, City, State, PostalCode, LicenseKey);
        }
        
        public System.Threading.Tasks.Task<PA2Reference.PhoneInfoResponse> BusinessPhoneAppend_QUERYGETJSONAsync(string BusinessName, string Address, string City, string State, string PostalCode, string LicenseKey)
        {
            return base.Channel.BusinessPhoneAppend_QUERYGETJSONAsync(BusinessName, Address, City, State, PostalCode, LicenseKey);
        }
        
        public System.Threading.Tasks.Task<PA2Reference.PhoneInfoResponse> BusinessPhoneAppend_GETXMLAsync(string BusinessName, string Address, string City, string State, string PostalCode, string LicenseKey)
        {
            return base.Channel.BusinessPhoneAppend_GETXMLAsync(BusinessName, Address, City, State, PostalCode, LicenseKey);
        }
        
        public System.Threading.Tasks.Task<PA2Reference.PhoneInfoResponse> BusinessPhoneAppend_GETJSONAsync(string BusinessName, string Address, string City, string State, string PostalCode, string LicenseKey)
        {
            return base.Channel.BusinessPhoneAppend_GETJSONAsync(BusinessName, Address, City, State, PostalCode, LicenseKey);
        }
        
        public System.Threading.Tasks.Task<PA2Reference.PhoneInfoResponse> BusinessPhoneAppend_POSTAsync(string BusinessName, string Address, string City, string State, string PostalCode, string LicenseKey)
        {
            return base.Channel.BusinessPhoneAppend_POSTAsync(BusinessName, Address, City, State, PostalCode, LicenseKey);
        }
        
        public System.Threading.Tasks.Task<PA2Reference.PhoneInfoResponse> BusinessPhoneAppend_PUTAsync(string BusinessName, string Address, string City, string State, string PostalCode, string LicenseKey)
        {
            return base.Channel.BusinessPhoneAppend_PUTAsync(BusinessName, Address, City, State, PostalCode, LicenseKey);
        }
        
        public System.Threading.Tasks.Task<PA2Reference.PhoneInfoResponse> BusinessPhoneAppend_DELETEAsync(string BusinessName, string Address, string City, string State, string PostalCode, string LicenseKey)
        {
            return base.Channel.BusinessPhoneAppend_DELETEAsync(BusinessName, Address, City, State, PostalCode, LicenseKey);
        }
        
        public System.Threading.Tasks.Task<PA2Reference.PhoneInfoResponse> BusinessPhoneAppendAsync(string BusinessName, string Address, string City, string State, string PostalCode, string LicenseKey)
        {
            return base.Channel.BusinessPhoneAppendAsync(BusinessName, Address, City, State, PostalCode, LicenseKey);
        }
        
        public System.Threading.Tasks.Task<PA2Reference.PhoneInfoResponse> CompositePhoneAppend_QUERYGETXMLAsync(string Name, string Address, string City, string State, string PostalCode, string isBusiness, string LicenseKey)
        {
            return base.Channel.CompositePhoneAppend_QUERYGETXMLAsync(Name, Address, City, State, PostalCode, isBusiness, LicenseKey);
        }
        
        public System.Threading.Tasks.Task<PA2Reference.PhoneInfoResponse> CompositePhoneAppend_QUERYGETJSONAsync(string Name, string Address, string City, string State, string PostalCode, string isBusiness, string LicenseKey)
        {
            return base.Channel.CompositePhoneAppend_QUERYGETJSONAsync(Name, Address, City, State, PostalCode, isBusiness, LicenseKey);
        }
        
        public System.Threading.Tasks.Task<PA2Reference.PhoneInfoResponse> CompositePhoneAppend_GETXMLAsync(string Name, string Address, string City, string State, string PostalCode, string isBusiness, string LicenseKey)
        {
            return base.Channel.CompositePhoneAppend_GETXMLAsync(Name, Address, City, State, PostalCode, isBusiness, LicenseKey);
        }
        
        public System.Threading.Tasks.Task<PA2Reference.PhoneInfoResponse> CompositePhoneAppend_GETJSONAsync(string Name, string Address, string City, string State, string PostalCode, string isBusiness, string LicenseKey)
        {
            return base.Channel.CompositePhoneAppend_GETJSONAsync(Name, Address, City, State, PostalCode, isBusiness, LicenseKey);
        }
        
        public System.Threading.Tasks.Task<PA2Reference.PhoneInfoResponse> CompositePhoneAppend_POSTAsync(string Name, string Address, string City, string State, string PostalCode, string isBusiness, string LicenseKey)
        {
            return base.Channel.CompositePhoneAppend_POSTAsync(Name, Address, City, State, PostalCode, isBusiness, LicenseKey);
        }
        
        public System.Threading.Tasks.Task<PA2Reference.PhoneInfoResponse> CompositePhoneAppend_PUTAsync(string Name, string Address, string City, string State, string PostalCode, string isBusiness, string LicenseKey)
        {
            return base.Channel.CompositePhoneAppend_PUTAsync(Name, Address, City, State, PostalCode, isBusiness, LicenseKey);
        }
        
        public System.Threading.Tasks.Task<PA2Reference.PhoneInfoResponse> CompositePhoneAppend_DELETEAsync(string Name, string Address, string City, string State, string PostalCode, string isBusiness, string LicenseKey)
        {
            return base.Channel.CompositePhoneAppend_DELETEAsync(Name, Address, City, State, PostalCode, isBusiness, LicenseKey);
        }
        
        public System.Threading.Tasks.Task<PA2Reference.PhoneInfoResponse> CompositePhoneAppendAsync(string Name, string Address, string City, string State, string PostalCode, string isBusiness, string LicenseKey)
        {
            return base.Channel.CompositePhoneAppendAsync(Name, Address, City, State, PostalCode, isBusiness, LicenseKey);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.soap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.soap))
            {
                return new System.ServiceModel.EndpointAddress("https://sws.serviceobjects.com/PA2/api.svc/soap");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return PhoneAppend2Client.GetBindingForEndpoint(EndpointConfiguration.soap);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return PhoneAppend2Client.GetEndpointAddress(EndpointConfiguration.soap);
        }
        
        public enum EndpointConfiguration
        {
            
            soap,
        }
    }
}
